apiVersion: v1
kind: Service
metadata:
  name: springboot-mysql-service
spec:
  selector:
    app: spring-mysql-aks
  ports:
  - port: 8080
    targetPort: 8080
    protocol: "TCP"
  type: LoadBalancer
