apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-aks-deploy
  labels:
    app: mysql-aks
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql-aks
      tier: database
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: mysql-aks
        tier: database
    spec:
      containers:
      - image: arm64v8/mysql:8.0.29-oracle
        name: mysql-aks
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-root
                key: password
          # - name: MYSQL_USER
          #   valueFrom:
          #     secretKeyRef:
          #       name: db-user
          #       key: username
          # - name: MYSQL_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: db-user
          #       key: password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: dbname

        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3307
          
        volumeMounts:
        - name: mysql-persistance-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistance-storage
          persistentVolumeClaim:
            claimName: mysql-aks-pvc
